### ISSUE TITLE
Questions about the ground truth trajectories of other agents? 

### ISSUE THREAD

**Issue by Jeff09** [MCZhi/Predictive-Decision#3]
Hi MCZhi, 

Thank you for sharing such an interesting work. I have some questions about those ground truth trajectories of other agents when training interaction-aware predictor. 

1. Do those ground truth trajectories of other agents are generated from log file and so are fixed during training? If so, how does it make sure that other agents will have corresponding reactions on the ego's planning trajectory?

2. What is the difference between the ego-conditioned auto-regressive planning method and traditional imitation learning methods?

**Comment by MCZhi** [comment]
Hi @Jeff09,

Thanks for your interest in our work. To answer your questions briefly:

1. Ground truth trajectories of other agents are generated from log files and remain fixed during training. However, these log files are created during the training process, containing data of other agents reacting to the ego vehicle's actions.
2. The auto-regressive planning method uses a GRU to implement the ego-conditioned operation and decode future trajectories of other agents in an auto-regressive manner. I don't really know what your traditional imitation learning methods stand for. Typically, traditional imitation learning generates actions (usually one step) for the ego vehicle without explicitly modeling the future behaviors of other agents. 

If you need further clarification, please let me know.
