### ISSUE TITLE
Questionabout pretrained ckpt

### ISSUE THREAD

**Issue by wheltz** [MCZhi/Predictive-Decision#5]
Thank you for your work. I have downloaded the pre-trained model ckpt you provided, but when I tested it, an error occurred. I can ensure that I installed the environment dependencies correctly, so how should I solve this problem?
```
RuntimeError: Error(s) in loading state_dict for Predictor:
        Unexpected key(s) in state_dict: "decoder.plan_input.weight", "decoder.plan_input.bias", "decoder.state_input.weight", "decoder.state_input.bias".
        size mismatch for decoder.cell.weight_ih: copying a param with shape torch.Size([1152, 128]) from checkpoint, the shape in current model is torch.Size([1152, 3]).
```

**Comment by MCZhi** [comment]
Hi, @wheltz, thank you for your interest. When testing the model, remember to include the `--use_interaction` argument in `test.py`.
